version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"


  database:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"

